sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes a long time
install: echo "skip bundle install"

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=lwrp-resources-ubuntu-1404

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - chef gem install danger

script: kitchen verify ${INSTANCE}
