sudo: required
dist: trusty

addons:
  apt:
    update: true
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.4.17-1

# Don't `bundle install` which takes a long time
install: echo "skip bundle install"

services: docker

stages:
  - unit
  - test

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=lwrp-resources-ubuntu-1404
  - INSTANCE=lwrp-resources-debian-8
  - INSTANCE=lwrp-resources-centos-6
  - INSTANCE=lwrp-resources-centos-7
  - INSTANCE=attribute-resources-linux-ubuntu-1404
  - INSTANCE=attribute-resources-linux-debian-8
  - INSTANCE=attribute-resources-linux-centos-6
  - INSTANCE=attribute-resources-linux-centos-7
  - INSTANCE=syslog-ubuntu-1404
  - INSTANCE=syslog-debian-8
  - INSTANCE=syslog-centos-6
  - INSTANCE=syslog-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - chef gem install danger

script: kitchen verify ${INSTANCE}

jobs:
  include:
    - stage: unit
      script: chef exec delivery local all
      env: UNIT_AND_LINT=1
